# Generated by Django 5.0 on 2026-02-01 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report_list',
            field=models.ManyToManyField(blank=True, related_name='reported_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='report_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
